#!/usr/bin/env python3
"""
Generate PowerPoint presentation from structured content.
Usage: python generate_ppt.py --output <output.pptx> --title "Title" --content <content.json>
       python generate_ppt.py --output <output.pptx> --title "Title" --slides <slides.json>
"""

import sys
import json
import argparse
import os

def create_presentation(title, slides, template_path=None, output_path="output.pptx"):
    """
    Create a PowerPoint presentation.
    
    Args:
        title: Presentation title
        slides: List of slide dicts with 'title' and 'content' (str or list of str)
        template_path: Optional template PPTX to use for styling
        output_path: Output file path
    """
    try:
        from pptx import Presentation
        from pptx.util import Inches, Pt
    except ImportError:
        return {"success": False, "error": "python-pptx not installed. Run: pip install python-pptx"}
    
    try:
        # Load template or create new
        if template_path and os.path.exists(template_path):
            prs = Presentation(template_path)
        else:
            prs = Presentation()
        
        # Title slide
        title_slide_layout = prs.slide_layouts[0]  # Title slide
        slide = prs.slides.add_slide(title_slide_layout)
        title_shape = slide.shapes.title
        subtitle = slide.placeholders[1]
        
        title_shape.text = title
        subtitle.text = f"Generated by Doc-to-PPT"
        
        # Content slides
        bullet_layout = prs.slide_layouts[1]  # Title and Content
        
        for slide_data in slides:
            slide_title = slide_data.get('title', 'Untitled')
            slide_content = slide_data.get('content', [])
            
            slide = prs.slides.add_slide(bullet_layout)
            shapes = slide.shapes
            title_shape = shapes.title
            body_shape = shapes.placeholders[1]
            
            title_shape.text = slide_title
            text_frame = body_shape.text_frame
            
            # Handle content as list or string
            if isinstance(slide_content, str):
                # Split by newlines
                items = [line.strip() for line in slide_content.split('\n') if line.strip()]
            else:
                items = slide_content
            
            for i, item in enumerate(items):
                if i == 0:
                    p = text_frame.paragraphs[0]
                else:
                    p = text_frame.add_paragraph()
                p.text = item
                p.level = 0
        
        prs.save(output_path)
        return {
            "success": True, 
            "output": output_path,
            "slides": len(prs.slides),
            "message": f"Created {len(prs.slides)} slides in {output_path}"
        }
        
    except Exception as e:
        return {"success": False, "error": str(e)}

def main():
    parser = argparse.ArgumentParser(description='Generate PowerPoint from content')
    parser.add_argument('--output', '-o', required=True, help='Output PPTX file path')
    parser.add_argument('--title', '-t', default='Presentation', help='Presentation title')
    parser.add_argument('--template', help='Template PPTX file to use for styling')
    parser.add_argument('--content', help='JSON file with content structure')
    parser.add_argument('--slides', help='JSON string or file with slides array')
    
    args = parser.parse_args()
    
    # Get slides
    slides = []
    if args.slides:
        if os.path.exists(args.slides):
            with open(args.slides, 'r', encoding='utf-8') as f:
                slides = json.load(f)
        else:
            try:
                slides = json.loads(args.slides)
            except:
                slides = [{"title": "Content", "content": args.slides}]
    elif args.content:
        with open(args.content, 'r', encoding='utf-8') as f:
            data = json.load(f)
            slides = data.get('slides', [data])
    else:
        # Read from stdin
        try:
            data = json.load(sys.stdin)
            slides = data.get('slides', [data])
        except:
            print(json.dumps({"success": False, "error": "No content provided"}))
            sys.exit(1)
    
    result = create_presentation(
        title=args.title,
        slides=slides,
        template_path=args.template,
        output_path=args.output
    )
    
    print(json.dumps(result, ensure_ascii=False, indent=2))

if __name__ == "__main__":
    main()
